name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: yarn install --immutable

      - name: Compile and test contracts
        run: |
          yarn foundry:compile
          yarn foundry:test

      - name: Lint
        run: yarn lint

      - name: Check typings on nextjs
        run: yarn next:check-types

      - name: Build nextjs
        run: yarn next:build
